= Problems in and with Web Development
:published_at: 2015-02-10
:hp-tags: Web Development, JavaScript, CSS, HTML

Hi everyone, how are you all!
Hope everything's good. 

I had been interacting with some of the Web Developers since last month. And after discussing with them; I came to conclusion that while developing for web, if it doesn't show any error, it is least bothered for correction or for the sake of coding style.

What can be the possible solution?

So we can inform the developer that it is wrong as per the coding style or it may lead to a possible bug.

I tried the editors which provide the Code Analysis; that is an explicit call to the analysis. Only few things like spell check, variable usage etc. But does help when we access any method from the unknown object in JavaScript i.e. Digging for the source of object and then resolution to its member method, or with CSS notifying about the position related issues, inability of certain properties to work in presence of other properties etc.

