= Importance of indentation while Coding
:published_at: 2015-02-18
:hp-tags: Coding, Web Development, JavaScript, CSS, HTML

Indentation, a very important thing to save yourself from readability problems!

.link:http://en.wikipedia.org/wiki/Indentation_(typesetting)[Wikipedia: Indentation (typesetting)]
[TIP]
An indentation is an empty space at the beginning of a line to signal the start of a new paragraph. Many computer languages have adopted this technique to designate "paragraphs" or other logical blocks in the program.

Taking indentation into consideration, we are making our code more readable for ourself and others.

=== Why indentation is recommended? Here are some aspects:

==== Readability

As it clearly shows how code in written and logically what heirarchy will it follow is very much clear from indentation. For example opening and closing of curly brace is at a perticular tab level(say 3 i.e. 3 tabs before the opening and closing curly braces) and all of its content code written at level 4(4 tabs) will clearly state the *_scope and heirarchy of code visually to the developer_*.

'''
==== Code Management

As readability gets improved, the code management also gets better. Suppose you have a code block of 200 lines. If it were without indentation; it would be very hard to determine where code block is getting completed, to make situation worse, you might be having several if...else block each 20-50 lines in length. And not visualize the code *_with proper indentation, it just as smooth as butter_*. +

Many editors(I must name link:http://www.sublimetext.com/[Sublime text]) provide the code folding feature on the basis of indentation used.

'''
==== Code Processing

You might have heard of the SASS. This CSS preprocessor strictly relies on the proper indentation and any imporper indentation will break the whole stylesheet. Now whats the benefit? It inforces this to ensure that the code is neat and clean. +

'''


So its good to indent the code, rather than just coding. Please share your experiences where indentation saved you. +
*_Happy Coding...:)_*